# SERVIDOR
#quarkus.http.port=${HTTP_PORT:8081}
quarkus.http.port=8081
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=*
quarkus.http.cors.headers=*

#OPCIONES DE COMPILACION
quarkus.package.type=uber-jar
quarkus.package.runner-suffix=_run
quarkus.package.output-name=str_seg

# LOGS
# LOGS CONSOLE
quarkus.log.console.enable=${LOG_CONSOLE:true}
quarkus.log.console.format=[%d{dd-MM-yyyy HH:mm:ss}] %5p [%t] (%F:%L) - %m%n
quarkus.log.console.color=true
quarkus.log.console.level=INFO
quarkus.log.category."io.quarkus".level=ERROR
# LOGS FILE
quarkus.log.file.enable=${LOG_FILE:false}
quarkus.log.file.path=${LOG_FILE_PATH:logs/server.log}
quarkus.log.file.level=${LOG_FILE_LEVEL:INFO}
quarkus.log.file.format=[%d{dd-MM-yyyy HH:mm:ss}] %5p [%t] (%F:%L) - %m%n
quarkus.log.file.rotation.max-file-size=${LOG_MAX_SIZE:10M}
quarkus.log.file.rotation.max-backup-index=${LOG_MAX_BACKUPS:10}
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.rotation.rotate-on-boot=false
quarkus.log.file.rotation.rotate-sync=true

# BASE DE DATOS
quarkus.datasource.db-kind = postgresql
quarkus.datasource.jdbc.url=${DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/sgp-pnl}
quarkus.datasource.username=${DATASOURCE_USERNAME:postgres}
quarkus.datasource.password=${DATASOURCE_PASSWORD:admin}
quarkus.datasource.jdbc.max-size=500
quarkus.datasource.jdbc.min-size=2
quarkus.hibernate-orm.database.generation=none
#quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.dialect=org.hibernate.dialect.CockroachDialect

